# Generated by Django 3.2.5 on 2023-10-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_course_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sem',
            field=models.PositiveIntegerField(),
        ),
    ]
