# Generated by Django 3.2.5 on 2023-10-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.PositiveBigIntegerField(default=4),
            preserve_default=False,
        ),
    ]
