# Generated by Django 3.2.5 on 2023-10-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], max_length=20),
        ),
    ]
